### ISSUE TITLE
Run out of memory and segfault reported?

### ISSUE THREAD

**Issue by uestcmahone** [sslab-gatech/hydra#10]
7.	After executing two concurrent tasks for ext4 and f2fs fuzz for about 36 hours on x86_64 server with 282GB memory , ext4-combined-consistency and f2fs-combined-consistency reported segfault, 
and I found there is not enough memory available, tmpfs-separate consumes almost all memory, is this a bug or is it caused by my misuse?

none           tmpfs     142G  142G     0 100% /tmp/mosbench/tmpfs-separate/1
none           tmpfs     142G  142G     0 100% /tmp/mosbench/tmpfs-separate/4

~/hydra/src$ free -m
                 total         used           free        shared     buff/cache    available
Mem:         289419        1510         1006      279783         286903          5485
Swap:          95366        9741       85625

**Comment by squizz617** [comment]
For performance, tmpfs uses the main memory instead of disk to store files. It seems that too many bug reports (logs and buggy disk images) were stored under tmpfs, and as a result your system ran out of memory. Segfault of `ext4-combined-consistency` must be another side-effect of that.
You can consider using a disk instead of tmpfs, or occasionally clearing the log directory.
