### ISSUE TITLE
how to enable kasan?

### ISSUE THREAD

**Issue by PKFXXXX** [sslab-gatech/hydra#12]
I started fuzzing according to the readme, the version of lkl is 5.0.0, but I suspected that kasan was not turned on, so I debugged it with gdb and found that the program did not execute kasan_malloc. 
Looking forward to your reply, thanks~

**Comment by bonzobudy225** [comment]
@PKFXXXX Hi, did you find out how to enable it? I think that I have similar problem, the fuzzer doesn't seem to be able to find memory errors for me.

**Comment by peng-hui** [comment]
By default, Hydra builds with the crash-inconsistency bugs using SymC3 with KASAN disabled. I find under the `src/ff-gcc` folder of Hydra, there actually are two source files, compiling into `ff-gcc` and `ff-gcc-kasan`, respectively. 
 
I cross-checked the code in the Janus repository and find the [`ff-gcc/ff-gcc.cc`](https://github.com/sslab-gatech/hydra/blob/master/src/ff-gcc/ff-gcc-kasan.cc) file in [Janus](https://github.com/sslab-gatech/janus) is almost identical with[ `ff-gcc/ff-gcc-kasan.cc`](https://github.com/sslab-gatech/janus/blob/master/ff-gcc/ff-gcc.cc) in Hydra, which means the `ff-gcc-karan` binary in Hydra is the one with KARAN enabled.

Given the truth that `ff-gcc` or `ff-gcc-karan` are used for lkl instrumentation, if you want to check memory corruptions, you shall use `ff-gcc-karan` instead of `ff-gcc`. 

Seeing the compilation script in `src/lkl/compile` currently uses `ff-gcc`, you can try to replace it with `ff-gcc-kasan`. 

https://github.com/sslab-gatech/janus/blob/58d9e85df86068f9532f28f45a7e2041b32a165c/lkl/compile#L32
```
subprocess.call('make -C tools/lkl -j CC="%s/../ff-gcc/ff-gcc fs/%s"' % (dir_path, args.type), shell=True)
```

Also, if you only want to detect memory corruptions only but not the crash-consistency bugs, you shall also edit the fuzzing running script `src/run.py`, from `xxx-combined-consistency` to `xxx-combined` or `xxx-executor`.
https://github.com/sslab-gatech/hydra/blob/da6dcc781e30ffe694088078ac206209527e9604/src/run.py#L70

-------------
However, even if I successfully compiled it with KARAN enabled, I still encountered other runtime errors when launching the fuzzer...

**Comment by squizz617** [comment]
[This patch](https://github.com/sslab-gatech/hydra/blob/master/src/patch/lkl-enable-kasan.patch) is a dump of the changes that were applied to LKL v4.18 to enable KASAN. Haven't tried patching the newer releases myself, but a file system developer recently told me he successfully ported this patch to make it working for LKL v5.4.
